### ISSUE TITLE
显示异常

### ISSUE THREAD

**Issue by AndroidKid19** [liyuhaolol/BasePopup-master#1]
showPopupWindow时宽没有填充   @@是什么问题?

 SlideFromTopPopup mSlideFromTopPopup = new SlideFromTopPopup(this,strLs,position);
        mSlideFromTopPopup.showPopupWindow(mLayoutDate);

package com.cskid.thacher.mvp.ui.view;

import android.annotation.SuppressLint;
import android.content.Context;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.view.animation.Animation;
import android.view.animation.OvershootInterpolator;
import android.view.animation.TranslateAnimation;

import com.cskid.thacher.R;
import com.cskid.thacher.mvp.ui.adapter.PopupAdapter;
import com.jess.arms.utils.ArmsUtils;

import java.util.List;

import razerdp.basepopup.BasePopupWindow;

/**
 * @description : TODO  从顶部下滑的Poup
 * @author : yuanweiwei
 * @date : 2019/1/3 15:07
 */
public class SlideFromTopPopup extends BasePopupWindow {

    /**
     * @description : TODO 定义点击事件接口
     * @author : yuanweiwei
     * @date : 2018/12/28 15:51
     * @return : null
     */
    public interface OnItemClickListener {
        void onItemClick(View view, int position);
    }

    private OnItemClickListener mOnItemClickListener;

    public void setOnItemClickListener(OnItemClickListener onItemClickListener) {
        mOnItemClickListener = onItemClickListener;
    }

    public SlideFromTopPopup(Context context,List<String> strLs,int position) {
        super(context);
        setBackPressEnable(false);
        setAlignBackground(true);
        RecyclerView mRecyclerView = findViewById(R.id.rv_content);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(context));
        PopupAdapter popupAdapter = new PopupAdapter(strLs);
        mRecyclerView.setAdapter(popupAdapter);
        popupAdapter.setSelection(position);
        popupAdapter.setOnItemClickListener(new PopupAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                mOnItemClickListener.onItemClick(view,position);
            }
        });
    }

    @Override
    protected Animation onCreateShowAnimation() {
        TranslateAnimation translateAnimation = new TranslateAnimation(0f, 0f, -ArmsUtils.dip2px(getContext(), 350f), 0);
        translateAnimation.setDuration(450);
        translateAnimation.setInterpolator(new OvershootInterpolator(1));
        return translateAnimation;
    }

    @SuppressLint("ResourceAsColor")
    @Override
    protected Animation onCreateDismissAnimation() {
        TranslateAnimation translateAnimation = new TranslateAnimation(0f, 0f, 0, -ArmsUtils.dip2px(getContext(), 350f));
        translateAnimation.setDuration(450);
        translateAnimation.setInterpolator(new OvershootInterpolator(-4));
        return translateAnimation;
    }

    @Override
    public View onCreateContentView() {
        return createPopupById(R.layout.layout_popup_date);
    }

}

**Comment by liyuhaolol** [comment]
推荐你去原作者那里问问啊，popwindow现在工作在高版本Android上就是有一些小问题，推荐不要使用包裹或者填充父布局，全部动态的计算一个固定数值设置进去，这样一般不会出问题，我现在写项目，一般用dialog代替popwindow，确实不是太好用
